export const PROPERTIES = [
  {
    id: "p-001",
    title: "Serenity Villas",
    price: 320000,
    address: "45 Maple Drive, New York",
    beds: 3,
    baths: 2,
    sqft: 1650,
    status: "For Sale",
    imageUrl: "/interior-modern-living-room.jpg",
    createdAt: "2025-09-18",
  },
  {
    id: "p-002",
    title: "Urban Oasis",
    price: 290000,
    address: "92 Lexington Ave, New York",
    beds: 2,
    baths: 2,
    sqft: 1230,
    status: "For Sale",
    imageUrl: "/home-office-bright.jpg",
    createdAt: "2025-09-12",
  },
  {
    id: "p-003",
    title: "Sunset Residences",
    price: 305000,
    address: "18 Sunset Blvd, Los Angeles",
    beds: 3,
    baths: 2,
    sqft: 1580,
    status: "For Sale",
    imageUrl: "/backyard-garden-patio.jpg",
    createdAt: "2025-09-05",
  },
  {
    id: "p-004",
    title: "Harborview Flats",
    price: 410000,
    address: "11 Bay Street, San Francisco",
    beds: 2,
    baths: 2,
    sqft: 1420,
    status: "For Sale",
    imageUrl: "/modern-kitchen.png",
    createdAt: "2025-08-24",
  },
  {
    id: "p-005",
    title: "Maple Grove House",
    price: 375000,
    address: "101 Grove St, Boston",
    beds: 4,
    baths: 3,
    sqft: 2090,
    status: "For Sale",
    imageUrl: "/neighborhood-aerial-real-estate.jpg",
    createdAt: "2025-08-18",
  },
  {
    id: "p-006",
    title: "Cedar Park Home",
    price: 265000,
    address: "77 Cedar Park, Austin",
    beds: 3,
    baths: 2,
    sqft: 1500,
    status: "For Sale",
    imageUrl: "/placeholder.jpg",
    createdAt: "2025-08-10",
  },
]

export const TESTIMONIALS = [
  { id: "t1", name: "Priya S.", quote: "A seamless buying experience and amazing support." },
  { id: "t2", name: "Rohit A.", quote: "Found our dream home faster than we expected!" },
  { id: "t3", name: "Anita K.", quote: "Professional, responsive, and truly helpful." },
  { id: "t4", name: "Karan V.", quote: "Excellent guidance from start to finish." },
  { id: "t5", name: "Nisha L.", quote: "Highly recommend for first-time buyers." },
]
